bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
set -g mouse on
bind c-j resize-pane -D 5
bind c-k resize-pane -U 5
bind c-h resize-pane -L 5
bind c-l resize-pane -R 5
